minswap/verified-tokens

tokens.json
Added Indigo iAssets Policy ID
Ref: https://cexplorer.io/policy/f66d78b4a3cb3d37afa0ec36461e51ecbde00f26c8f0a68f94b69880
=> Added iAssets Policy ID.

tokens.json
Added telegram, discord, and coinGecko
=> update $TOSI with more links on tokens.json

tokens.json
=> Added Yamfore

tokens.json
ref: https://github.com/minswap/verified-tokens/pull/5
=> Added Cavalier King Charles Token

tokens.json
=> Added Wolf Cardano token.

tokens.json
Added $FIRE Token for verification
Tweet showing policy ID (one year ago tomorrow!): https://twitter.com/FireTokenADA/status/1467430697962852352?s=20&t=fx9SPx4Ip1eJLzQfbZXaKw 
Policy ID is also posted on our website in the footer on the bottom of the page.
=> Update tokens.json - Add $FIRE Token

tokens.json
Signed-off-by: Nguyen Le Vu Long <vulongvn98@gmail.com>
=> add IAG (Iagon) token

tokens.json
This PR adds the policy id of the SNOW token to tokens.json
=> Add SNOW token to tokens.json

tokens.json
Please verify GENS token, from Genius Yield
=> Add GENS - Genius Yield Token

Mtc
=> Mithrandir Coin

tokens.json
https://twitter.com/cryptodino_io/status/1611457278204338176?s=46&t=EtCnifNeGITmEdYvFoPW5g
=> Adding DINO policy for CryptoDino ecosystem

tokens.json
The policy ID is listed at the bottom of the [project website](https://saltyseagulls.io)
=> Verify Salty Seagulls Society $SALTY Token

tokens.json
Venom is the official token for the Platypus Cyberpunks and Whimsy projects.
=> Adding Venom Token

tokens.json
Policy Id will be added on the website and twitter shortly, I,ve been mandated to do the PR for the project.
Thank you
=> Eternal token

tokens.json
Added TOKEN info at the end of token.json for verification
=> verify TOKEN

tokens.json
IP Issue has been solved with new token image.
All community information included. Thank you for your time and effort.
=> Update tokens.json Verify DEAN

tokens.json
Please wait to merge this before Friday, 11:59PM.  We have not launched our pool yet.
=> $NGMI Token Verification

tokens.json
Pool will be created after initial distribution is complete, shortly after 23:00 EST May 4th 2023.
=> $peepee token verification

tokens.json
=> TestnetCoins vADA and pADA

tokens.json
Reverts minswap/verified-tokens#204
=> Revert "Verify Mynth Token"

tokens.json
Updated twitter and web URLs for GINKO
=> Update tokens.json for GINKO 

tokens.json
Add CHRY the official CherryLend Token
=> Add CHRY the official CherryLend Token

tokens.json
Both projects have non-existent Twitter accounts
=> Removed tokens

tokens.json
=> Add BLOCK token

tokens.json
=> Add HYDRA Token (Update tokens.json)

tokens.json
My formatter removed the trailing new line at the end of the file. Let me know if that's an issue. 
Also I added a discord link to the txpipe server for help running a miner. Is that fine?
=> add TUNA to verified tokens

tokens.json
Hi! This PR includes information about the JPG token.
=> Verify JPG token

tokens.json
Adding $BOOK for verification. You can see our policy id in our [Twitter bio](https://twitter.com/book_io) and [on our site](https://app.book.io/ito/sale).
=> adds $BOOK for verification.

tokens.json
Requesting SKILL token to be verified on the Minswap APP. :)
=> SKILL TOKEN

tokens.json
=> Update tokens.json - SWAN

tokens.json
Updating MarketRaker Social links
=> Update MarketRaker Social links

tokens.json
Reverts minswap/verified-tokens#561
=> Revert "FLDT added"

tokens.json
Add EBTC to verified tokens on minswap
=> Add EBTC to verified tokens .Update tokens.json

tokens.json
Added socials for the USDM token.
=> Add mehen socials

tokens.json
=> add Drachma token

tokens.json
=> verify $MANE token

tokens.json
```
"7088ad38a23e997dc6ab90336cae582c93b61460888d83f178899a33": {
"project": "KOI",
"categories": ["NFT", "AI", "Other"],
"socialLinks": {
"website": "http://koicoinada.com/",
"twitter": "https://twitter.com/koicoinofficial",
"discord": "https://discord.gg/XHA8qHtba5"
}
}
```
=> Add KOI token to verified token list

tokens.json
Request to verify ADA BOIS token.
Thank You
=> Add ADA BOIS

tokens.json
This PR adds the Book.io BEARD token, a fungible token that _is_ also a book.
=> Adds Book.io BEARD token

tokens.json
=> Add Exo, Hexo Tokens

tokens.json
Verifying the Star Force Utility Token for MinswapDEX.
=> Star Force Utility Token

tokens.json
=> Add Mustachio - SnekX

tokens.json
=> Add SNEK MAGE - SnekX

tokens.json
=> Add PAPA SNEK - SnekX

tokens.json
=> Add GRANDMA SNEK - SnekX

tokens.json
=> Add Lil Snekkie - SnekX

tokens.json
=> Add Gummy - SnekX

tokens.json
=> Add Cardano Nuts - SnekX

tokens.json
Please verify ELEMENT Token via the tokens.json file change.
=> Verify ELEMENT Token

tokens.json
=> Added MUNGUS token

tokens.json
=> add clarity

tokens.json
=> Add GmCat - SnekX

tokens.json
=> Add GameStop - SnekX

tokens.json
=> Add PaidXPO - SnekX

tokens.json
=> Add RelaxAI

tokens.json
=> Add SNOQ - SnekX

tokens.json
=> Add SPLISH - SnekX

tokens.json
=> Add ANDY - SnekX

tokens.json
=> Verify $Change

tokens.json
=> Add PIGEON - SnekX

tokens.json
=> Add EAT - SnekX

tokens.json
=> Add TECH - SnekX

tokens.json
=> Add DANZO - SnekX

tokens.json
=> Add Butcher Chang Hoskinson - SnekX

tokens.json
=> Add Pepe on ADA - SnekX

tokens.json
=> Add Reeboka Hoskinson - SnekX

tokens.json
=> Add SWINE - SnekX

tokens.json
=> Add NIKEGIRL - SnekX

tokens.json
=> Add Squirt - SnekX

tokens.json
=> Add Jorge - SnekX

tokens.json
Just merge it. He's a good pig.
=> Update $NIKE listing

tokens.json
=> Add MIKE - SnekX

tokens.json
=> Add Slurp - SnekX

tokens.json
=> Add PUMBA - SnekX

tokens.json
=> Add EKIN - SnekX

tokens.json
=> Add RUBAK - SnekX

tokens.json
=> Add Pink Dolphin ADA - SnekX

tokens.json
=> Add RIPPABLO - SnekX

tokens.json
=> Add Chairman Meow - SnekX

tokens.json
=> Add SPAM - SnekX

tokens.json
=> Add The Rats - SnekX

tokens.json
=> Add GYROS - SnekX

tokens.json
=> Add PrAda - SnekX

tokens.json
=> Add Brett - SnekX

tokens.json
=> Add CATERALL - SnekX

tokens.json
=> Add GINA - SnekX

tokens.json
=> Add Secirity - SnekX

tokens.json
=> Add RFK - SnekX

tokens.json
=> Add BORK - SnekX

tokens.json
=> Add CRAZY MARY - SnekX

tokens.json
=> Add Peipei - SnekX

tokens.json
=> Add EL RISITAS - SnekX

tokens.json
=> Add GPT - SnekX

tokens.json
=> Add Charless Ranch - SnekX

tokens.json
Please review and merge this new token addition.
=> Add new token: 0411fdd6dbfc5aedac7a1fb68688e756e1de99426ff68d67a475b950

tokens.json
=> Verify GoblinGang token

tokens.json
=> Verify MARTIN token

tokens.json
=> Add Potty - SnekX

tokens.json
=> Add Charl Husken - SnekX

tokens.json
=> Add CETARDIO - SnekX

tokens.json
=> Add Meem - SnekX

tokens.json
=> Update Ssss Twitter

tokens.json
=> Add analos - SnekX

tokens.json
=> verify Nextfi tokens.json

tokens.json
=> Add CHANG HARD SPORK - SnekX

tokens.json
=> Add Controller Drift - SnekX

tokens.json
=> Add BombaClaat - SnekX

tokens.json
=> Add Bum - SnekX

tokens.json
=> Add Volume

tokens.json
=> Add COFE - SnekX

tokens.json
=> Add MAGA INU - SnekX

tokens.json
Added token verification acording to the instructions.
=> VERIFY MOM TOKEN

tokens.json
Added bally token with correct socials
=> Add Bally Token

tokens.json
adding reit tokens for verification on minswap
=> added reitcircles
